//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFShopVinyl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public tblEmployee()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<int> BossID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeLastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
        public string JobDescription { get; set; }
    
        public virtual tblBoss tblBoss { get; set; }
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
