//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFShopVinyl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOffice
    {
        public tblOffice()
        {
            this.tblBosses = new HashSet<tblBoss>();
        }
    
        public int OfficeID { get; set; }
        public string OfficeName { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
    
        public virtual ICollection<tblBoss> tblBosses { get; set; }
    }
}
