//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFShopVinyl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VinylRecordsShopEntities : DbContext
    {
        public VinylRecordsShopEntities()
            : base("name=VinylRecordsShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAlbum> tblAlbums { get; set; }
        public virtual DbSet<tblArtist> tblArtists { get; set; }
        public virtual DbSet<tblBoss> tblBosses { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblGenre> tblGenres { get; set; }
        public virtual DbSet<tblOffice> tblOffices { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<vwAlbum> vwAlbums { get; set; }
        public virtual DbSet<vwArtist> vwArtists { get; set; }
        public virtual DbSet<vwBoss> vwBosses { get; set; }
        public virtual DbSet<vwCustomer> vwCustomers { get; set; }
        public virtual DbSet<vwEmployee> vwEmployees { get; set; }
        public virtual DbSet<vwGenre> vwGenres { get; set; }
        public virtual DbSet<vwOffice> vwOffices { get; set; }
        public virtual DbSet<vwOrder> vwOrders { get; set; }
        public virtual DbSet<vwUser> vwUsers { get; set; }
    }
}
