//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFShopVinyl
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBoss
    {
        public int BossID { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public string BossName { get; set; }
        public string BossLastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
        public string JobDescritions { get; set; }
        public int Expr1 { get; set; }
        public string OfficeName { get; set; }
    }
}
