//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFShopVinyl
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string TotalPrice { get; set; }
        public Nullable<int> NumberOfPieces { get; set; }
        public int Expr1 { get; set; }
        public string Name { get; set; }
        public int Expr2 { get; set; }
        public string EmployeeName { get; set; }
        public int Expr3 { get; set; }
        public string Title { get; set; }
    }
}
