//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFShop.ServiceReferenceShop {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwUser", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwOffice", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwOffice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OfficeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeID {
            get {
                return this.OfficeIDField;
            }
            set {
                if ((this.OfficeIDField.Equals(value) != true)) {
                    this.OfficeIDField = value;
                    this.RaisePropertyChanged("OfficeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeName {
            get {
                return this.OfficeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeNameField, value) != true)) {
                    this.OfficeNameField = value;
                    this.RaisePropertyChanged("OfficeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwBoss", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwBoss : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        public override string ToString()
        {
            return String.Format("{0} {1}", BossName, BossLastName);
        }

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BossIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BossLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BossNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobDescritionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OfficeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BossID {
            get {
                return this.BossIDField;
            }
            set {
                if ((this.BossIDField.Equals(value) != true)) {
                    this.BossIDField = value;
                    this.RaisePropertyChanged("BossID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BossLastName {
            get {
                return this.BossLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BossLastNameField, value) != true)) {
                    this.BossLastNameField = value;
                    this.RaisePropertyChanged("BossLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BossName {
            get {
                return this.BossNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BossNameField, value) != true)) {
                    this.BossNameField = value;
                    this.RaisePropertyChanged("BossName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr1 {
            get {
                return this.Expr1Field;
            }
            set {
                if ((this.Expr1Field.Equals(value) != true)) {
                    this.Expr1Field = value;
                    this.RaisePropertyChanged("Expr1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobDescritions {
            get {
                return this.JobDescritionsField;
            }
            set {
                if ((object.ReferenceEquals(this.JobDescritionsField, value) != true)) {
                    this.JobDescritionsField = value;
                    this.RaisePropertyChanged("JobDescritions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OfficeID {
            get {
                return this.OfficeIDField;
            }
            set {
                if ((this.OfficeIDField.Equals(value) != true)) {
                    this.OfficeIDField = value;
                    this.RaisePropertyChanged("OfficeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeName {
            get {
                return this.OfficeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeNameField, value) != true)) {
                    this.OfficeNameField = value;
                    this.RaisePropertyChanged("OfficeName");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwEmployee", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwEmployee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        public override string ToString()
        {
            return String.Format("{0} {1}", EmployeeName, EmployeeLastName);
        }

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BossIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BossNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BossID {
            get {
                return this.BossIDField;
            }
            set {
                if ((this.BossIDField.Equals(value) != true)) {
                    this.BossIDField = value;
                    this.RaisePropertyChanged("BossID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BossName {
            get {
                return this.BossNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BossNameField, value) != true)) {
                    this.BossNameField = value;
                    this.RaisePropertyChanged("BossName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeLastName {
            get {
                return this.EmployeeLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeLastNameField, value) != true)) {
                    this.EmployeeLastNameField = value;
                    this.RaisePropertyChanged("EmployeeLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr1 {
            get {
                return this.Expr1Field;
            }
            set {
                if ((this.Expr1Field.Equals(value) != true)) {
                    this.Expr1Field = value;
                    this.RaisePropertyChanged("Expr1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobDescription {
            get {
                return this.JobDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.JobDescriptionField, value) != true)) {
                    this.JobDescriptionField = value;
                    this.RaisePropertyChanged("JobDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwOrder", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AlbumIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberOfPiecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AlbumID {
            get {
                return this.AlbumIDField;
            }
            set {
                if ((this.AlbumIDField.Equals(value) != true)) {
                    this.AlbumIDField = value;
                    this.RaisePropertyChanged("AlbumID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr1 {
            get {
                return this.Expr1Field;
            }
            set {
                if ((this.Expr1Field.Equals(value) != true)) {
                    this.Expr1Field = value;
                    this.RaisePropertyChanged("Expr1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr2 {
            get {
                return this.Expr2Field;
            }
            set {
                if ((this.Expr2Field.Equals(value) != true)) {
                    this.Expr2Field = value;
                    this.RaisePropertyChanged("Expr2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr3 {
            get {
                return this.Expr3Field;
            }
            set {
                if ((this.Expr3Field.Equals(value) != true)) {
                    this.Expr3Field = value;
                    this.RaisePropertyChanged("Expr3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfPieces {
            get {
                return this.NumberOfPiecesField;
            }
            set {
                if ((this.NumberOfPiecesField.Equals(value) != true)) {
                    this.NumberOfPiecesField = value;
                    this.RaisePropertyChanged("NumberOfPieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalPriceField, value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwAlbum", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwAlbum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlbumIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ArtistIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expr2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GenreIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StorageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlbumID {
            get {
                return this.AlbumIDField;
            }
            set {
                if ((this.AlbumIDField.Equals(value) != true)) {
                    this.AlbumIDField = value;
                    this.RaisePropertyChanged("AlbumID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ArtistID {
            get {
                return this.ArtistIDField;
            }
            set {
                if ((this.ArtistIDField.Equals(value) != true)) {
                    this.ArtistIDField = value;
                    this.RaisePropertyChanged("ArtistID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistName {
            get {
                return this.ArtistNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistNameField, value) != true)) {
                    this.ArtistNameField = value;
                    this.RaisePropertyChanged("ArtistName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr1 {
            get {
                return this.Expr1Field;
            }
            set {
                if ((this.Expr1Field.Equals(value) != true)) {
                    this.Expr1Field = value;
                    this.RaisePropertyChanged("Expr1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expr2 {
            get {
                return this.Expr2Field;
            }
            set {
                if ((this.Expr2Field.Equals(value) != true)) {
                    this.Expr2Field = value;
                    this.RaisePropertyChanged("Expr2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GenreID {
            get {
                return this.GenreIDField;
            }
            set {
                if ((this.GenreIDField.Equals(value) != true)) {
                    this.GenreIDField = value;
                    this.RaisePropertyChanged("GenreID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Storage {
            get {
                return this.StorageField;
            }
            set {
                if ((this.StorageField.Equals(value) != true)) {
                    this.StorageField = value;
                    this.RaisePropertyChanged("Storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwGenre", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwGenre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenreIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenreID {
            get {
                return this.GenreIDField;
            }
            set {
                if ((this.GenreIDField.Equals(value) != true)) {
                    this.GenreIDField = value;
                    this.RaisePropertyChanged("GenreID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwArtist", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwArtist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistID {
            get {
                return this.ArtistIDField;
            }
            set {
                if ((this.ArtistIDField.Equals(value) != true)) {
                    this.ArtistIDField = value;
                    this.RaisePropertyChanged("ArtistID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistName {
            get {
                return this.ArtistNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistNameField, value) != true)) {
                    this.ArtistNameField = value;
                    this.RaisePropertyChanged("ArtistName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwCustomer", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class vwCustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        public override string ToString()
        {
            return String.Format("{0} {1}", Name, LastName);
        }

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFShopVinyl")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceShop.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUser", ReplyAction="http://tempuri.org/IService1/GetAllUserResponse")]
        WPFShop.ServiceReferenceShop.vwUser[] GetAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUser", ReplyAction="http://tempuri.org/IService1/GetAllUserResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwUser[]> GetAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllOffice", ReplyAction="http://tempuri.org/IService1/GetAllOfficeResponse")]
        WPFShop.ServiceReferenceShop.vwOffice[] GetAllOffice(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllOffice", ReplyAction="http://tempuri.org/IService1/GetAllOfficeResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwOffice[]> GetAllOfficeAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBoss", ReplyAction="http://tempuri.org/IService1/GetAllBossResponse")]
        WPFShop.ServiceReferenceShop.vwBoss[] GetAllBoss(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBoss", ReplyAction="http://tempuri.org/IService1/GetAllBossResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwBoss[]> GetAllBossAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllEmployee", ReplyAction="http://tempuri.org/IService1/GetAllEmployeeResponse")]
        WPFShop.ServiceReferenceShop.vwEmployee[] GetAllEmployee(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllEmployee", ReplyAction="http://tempuri.org/IService1/GetAllEmployeeResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwEmployee[]> GetAllEmployeeAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllOrder", ReplyAction="http://tempuri.org/IService1/GetAllOrderResponse")]
        WPFShop.ServiceReferenceShop.vwOrder[] GetAllOrder(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllOrder", ReplyAction="http://tempuri.org/IService1/GetAllOrderResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwOrder[]> GetAllOrderAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAlbum", ReplyAction="http://tempuri.org/IService1/GetAllAlbumResponse")]
        WPFShop.ServiceReferenceShop.vwAlbum[] GetAllAlbum(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAlbum", ReplyAction="http://tempuri.org/IService1/GetAllAlbumResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwAlbum[]> GetAllAlbumAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGenre", ReplyAction="http://tempuri.org/IService1/GetAllGenreResponse")]
        WPFShop.ServiceReferenceShop.vwGenre[] GetAllGenre(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGenre", ReplyAction="http://tempuri.org/IService1/GetAllGenreResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwGenre[]> GetAllGenreAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllArtist", ReplyAction="http://tempuri.org/IService1/GetAllArtistResponse")]
        WPFShop.ServiceReferenceShop.vwArtist[] GetAllArtist(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllArtist", ReplyAction="http://tempuri.org/IService1/GetAllArtistResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwArtist[]> GetAllArtistAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCustomer", ReplyAction="http://tempuri.org/IService1/GetAllCustomerResponse")]
        WPFShop.ServiceReferenceShop.vwCustomer[] GetAllCustomer(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCustomer", ReplyAction="http://tempuri.org/IService1/GetAllCustomerResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwCustomer[]> GetAllCustomerAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOffice", ReplyAction="http://tempuri.org/IService1/AddOfficeResponse")]
        WPFShop.ServiceReferenceShop.vwOffice AddOffice(WPFShop.ServiceReferenceShop.vwOffice office);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOffice", ReplyAction="http://tempuri.org/IService1/AddOfficeResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwOffice> AddOfficeAsync(WPFShop.ServiceReferenceShop.vwOffice office);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOffice", ReplyAction="http://tempuri.org/IService1/DeleteOfficeResponse")]
        void DeleteOffice(int officeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOffice", ReplyAction="http://tempuri.org/IService1/DeleteOfficeResponse")]
        System.Threading.Tasks.Task DeleteOfficeAsync(int officeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsOfficeID", ReplyAction="http://tempuri.org/IService1/IsOfficeIDResponse")]
        bool IsOfficeID(int officeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsOfficeID", ReplyAction="http://tempuri.org/IService1/IsOfficeIDResponse")]
        System.Threading.Tasks.Task<bool> IsOfficeIDAsync(int officeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBoss", ReplyAction="http://tempuri.org/IService1/AddBossResponse")]
        WPFShop.ServiceReferenceShop.vwBoss AddBoss(WPFShop.ServiceReferenceShop.vwBoss boss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBoss", ReplyAction="http://tempuri.org/IService1/AddBossResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwBoss> AddBossAsync(WPFShop.ServiceReferenceShop.vwBoss boss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBoss", ReplyAction="http://tempuri.org/IService1/DeleteBossResponse")]
        void DeleteBoss(int bossID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBoss", ReplyAction="http://tempuri.org/IService1/DeleteBossResponse")]
        System.Threading.Tasks.Task DeleteBossAsync(int bossID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        WPFShop.ServiceReferenceShop.vwEmployee AddEmployee(WPFShop.ServiceReferenceShop.vwEmployee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwEmployee> AddEmployeeAsync(WPFShop.ServiceReferenceShop.vwEmployee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        void DeleteEmployee(int employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        WPFShop.ServiceReferenceShop.vwOrder AddOrder(WPFShop.ServiceReferenceShop.vwOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwOrder> AddOrderAsync(WPFShop.ServiceReferenceShop.vwOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        void DeleteOrder(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        System.Threading.Tasks.Task DeleteOrderAsync(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsOrderStorage", ReplyAction="http://tempuri.org/IService1/IsOrderStorageResponse")]
        bool IsOrderStorage(int albumId, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsOrderStorage", ReplyAction="http://tempuri.org/IService1/IsOrderStorageResponse")]
        System.Threading.Tasks.Task<bool> IsOrderStorageAsync(int albumId, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsOrderStorageEDIT", ReplyAction="http://tempuri.org/IService1/IsOrderStorageEDITResponse")]
        bool IsOrderStorageEDIT(int orderID, int albumId, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsOrderStorageEDIT", ReplyAction="http://tempuri.org/IService1/IsOrderStorageEDITResponse")]
        System.Threading.Tasks.Task<bool> IsOrderStorageEDITAsync(int orderID, int albumId, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAlbum", ReplyAction="http://tempuri.org/IService1/AddAlbumResponse")]
        WPFShop.ServiceReferenceShop.vwAlbum AddAlbum(WPFShop.ServiceReferenceShop.vwAlbum album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAlbum", ReplyAction="http://tempuri.org/IService1/AddAlbumResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwAlbum> AddAlbumAsync(WPFShop.ServiceReferenceShop.vwAlbum album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAlbum", ReplyAction="http://tempuri.org/IService1/DeleteAlbumResponse")]
        void DeleteAlbum(int albumID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAlbum", ReplyAction="http://tempuri.org/IService1/DeleteAlbumResponse")]
        System.Threading.Tasks.Task DeleteAlbumAsync(int albumID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGenre", ReplyAction="http://tempuri.org/IService1/AddGenreResponse")]
        WPFShop.ServiceReferenceShop.vwGenre AddGenre(WPFShop.ServiceReferenceShop.vwGenre genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGenre", ReplyAction="http://tempuri.org/IService1/AddGenreResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwGenre> AddGenreAsync(WPFShop.ServiceReferenceShop.vwGenre genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGenre", ReplyAction="http://tempuri.org/IService1/DeleteGenreResponse")]
        void DeleteGenre(int genreID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGenre", ReplyAction="http://tempuri.org/IService1/DeleteGenreResponse")]
        System.Threading.Tasks.Task DeleteGenreAsync(int genreID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArtist", ReplyAction="http://tempuri.org/IService1/AddArtistResponse")]
        WPFShop.ServiceReferenceShop.vwArtist AddArtist(WPFShop.ServiceReferenceShop.vwArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArtist", ReplyAction="http://tempuri.org/IService1/AddArtistResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwArtist> AddArtistAsync(WPFShop.ServiceReferenceShop.vwArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteArtist", ReplyAction="http://tempuri.org/IService1/DeleteArtistResponse")]
        void DeleteArtist(int artistID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteArtist", ReplyAction="http://tempuri.org/IService1/DeleteArtistResponse")]
        System.Threading.Tasks.Task DeleteArtistAsync(int artistID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomer", ReplyAction="http://tempuri.org/IService1/AddCustomerResponse")]
        WPFShop.ServiceReferenceShop.vwCustomer AddCustomer(WPFShop.ServiceReferenceShop.vwCustomer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomer", ReplyAction="http://tempuri.org/IService1/AddCustomerResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwCustomer> AddCustomerAsync(WPFShop.ServiceReferenceShop.vwCustomer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        void DeleteCustomer(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        System.Threading.Tasks.Task DeleteCustomerAsync(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WPFShop.ServiceReferenceShop.CompositeType GetDataUsingDataContract(WPFShop.ServiceReferenceShop.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.CompositeType> GetDataUsingDataContractAsync(WPFShop.ServiceReferenceShop.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WPFShop.ServiceReferenceShop.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WPFShop.ServiceReferenceShop.IService1>, WPFShop.ServiceReferenceShop.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFShop.ServiceReferenceShop.vwUser[] GetAllUser() {
            return base.Channel.GetAllUser();
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwUser[]> GetAllUserAsync() {
            return base.Channel.GetAllUserAsync();
        }
        
        public WPFShop.ServiceReferenceShop.vwOffice[] GetAllOffice(string search) {
            return base.Channel.GetAllOffice(search);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwOffice[]> GetAllOfficeAsync(string search) {
            return base.Channel.GetAllOfficeAsync(search);
        }
        
        public WPFShop.ServiceReferenceShop.vwBoss[] GetAllBoss(string search) {
            return base.Channel.GetAllBoss(search);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwBoss[]> GetAllBossAsync(string search) {
            return base.Channel.GetAllBossAsync(search);
        }
        
        public WPFShop.ServiceReferenceShop.vwEmployee[] GetAllEmployee(string search) {
            return base.Channel.GetAllEmployee(search);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwEmployee[]> GetAllEmployeeAsync(string search) {
            return base.Channel.GetAllEmployeeAsync(search);
        }
        
        public WPFShop.ServiceReferenceShop.vwOrder[] GetAllOrder(string search) {
            return base.Channel.GetAllOrder(search);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwOrder[]> GetAllOrderAsync(string search) {
            return base.Channel.GetAllOrderAsync(search);
        }
        
        public WPFShop.ServiceReferenceShop.vwAlbum[] GetAllAlbum(string search) {
            return base.Channel.GetAllAlbum(search);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwAlbum[]> GetAllAlbumAsync(string search) {
            return base.Channel.GetAllAlbumAsync(search);
        }
        
        public WPFShop.ServiceReferenceShop.vwGenre[] GetAllGenre(string search) {
            return base.Channel.GetAllGenre(search);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwGenre[]> GetAllGenreAsync(string search) {
            return base.Channel.GetAllGenreAsync(search);
        }
        
        public WPFShop.ServiceReferenceShop.vwArtist[] GetAllArtist(string search) {
            return base.Channel.GetAllArtist(search);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwArtist[]> GetAllArtistAsync(string search) {
            return base.Channel.GetAllArtistAsync(search);
        }
        
        public WPFShop.ServiceReferenceShop.vwCustomer[] GetAllCustomer(string search) {
            return base.Channel.GetAllCustomer(search);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwCustomer[]> GetAllCustomerAsync(string search) {
            return base.Channel.GetAllCustomerAsync(search);
        }
        
        public WPFShop.ServiceReferenceShop.vwOffice AddOffice(WPFShop.ServiceReferenceShop.vwOffice office) {
            return base.Channel.AddOffice(office);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwOffice> AddOfficeAsync(WPFShop.ServiceReferenceShop.vwOffice office) {
            return base.Channel.AddOfficeAsync(office);
        }
        
        public void DeleteOffice(int officeID) {
            base.Channel.DeleteOffice(officeID);
        }
        
        public System.Threading.Tasks.Task DeleteOfficeAsync(int officeID) {
            return base.Channel.DeleteOfficeAsync(officeID);
        }
        
        public bool IsOfficeID(int officeId) {
            return base.Channel.IsOfficeID(officeId);
        }
        
        public System.Threading.Tasks.Task<bool> IsOfficeIDAsync(int officeId) {
            return base.Channel.IsOfficeIDAsync(officeId);
        }
        
        public WPFShop.ServiceReferenceShop.vwBoss AddBoss(WPFShop.ServiceReferenceShop.vwBoss boss) {
            return base.Channel.AddBoss(boss);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwBoss> AddBossAsync(WPFShop.ServiceReferenceShop.vwBoss boss) {
            return base.Channel.AddBossAsync(boss);
        }
        
        public void DeleteBoss(int bossID) {
            base.Channel.DeleteBoss(bossID);
        }
        
        public System.Threading.Tasks.Task DeleteBossAsync(int bossID) {
            return base.Channel.DeleteBossAsync(bossID);
        }
        
        public WPFShop.ServiceReferenceShop.vwEmployee AddEmployee(WPFShop.ServiceReferenceShop.vwEmployee employee) {
            return base.Channel.AddEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwEmployee> AddEmployeeAsync(WPFShop.ServiceReferenceShop.vwEmployee employee) {
            return base.Channel.AddEmployeeAsync(employee);
        }
        
        public void DeleteEmployee(int employeeID) {
            base.Channel.DeleteEmployee(employeeID);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int employeeID) {
            return base.Channel.DeleteEmployeeAsync(employeeID);
        }
        
        public WPFShop.ServiceReferenceShop.vwOrder AddOrder(WPFShop.ServiceReferenceShop.vwOrder order) {
            return base.Channel.AddOrder(order);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwOrder> AddOrderAsync(WPFShop.ServiceReferenceShop.vwOrder order) {
            return base.Channel.AddOrderAsync(order);
        }
        
        public void DeleteOrder(int orderID) {
            base.Channel.DeleteOrder(orderID);
        }
        
        public System.Threading.Tasks.Task DeleteOrderAsync(int orderID) {
            return base.Channel.DeleteOrderAsync(orderID);
        }
        
        public bool IsOrderStorage(int albumId, int number) {
            return base.Channel.IsOrderStorage(albumId, number);
        }
        
        public System.Threading.Tasks.Task<bool> IsOrderStorageAsync(int albumId, int number) {
            return base.Channel.IsOrderStorageAsync(albumId, number);
        }
        
        public bool IsOrderStorageEDIT(int orderID, int albumId, int number) {
            return base.Channel.IsOrderStorageEDIT(orderID, albumId, number);
        }
        
        public System.Threading.Tasks.Task<bool> IsOrderStorageEDITAsync(int orderID, int albumId, int number) {
            return base.Channel.IsOrderStorageEDITAsync(orderID, albumId, number);
        }
        
        public WPFShop.ServiceReferenceShop.vwAlbum AddAlbum(WPFShop.ServiceReferenceShop.vwAlbum album) {
            return base.Channel.AddAlbum(album);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwAlbum> AddAlbumAsync(WPFShop.ServiceReferenceShop.vwAlbum album) {
            return base.Channel.AddAlbumAsync(album);
        }
        
        public void DeleteAlbum(int albumID) {
            base.Channel.DeleteAlbum(albumID);
        }
        
        public System.Threading.Tasks.Task DeleteAlbumAsync(int albumID) {
            return base.Channel.DeleteAlbumAsync(albumID);
        }
        
        public WPFShop.ServiceReferenceShop.vwGenre AddGenre(WPFShop.ServiceReferenceShop.vwGenre genre) {
            return base.Channel.AddGenre(genre);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwGenre> AddGenreAsync(WPFShop.ServiceReferenceShop.vwGenre genre) {
            return base.Channel.AddGenreAsync(genre);
        }
        
        public void DeleteGenre(int genreID) {
            base.Channel.DeleteGenre(genreID);
        }
        
        public System.Threading.Tasks.Task DeleteGenreAsync(int genreID) {
            return base.Channel.DeleteGenreAsync(genreID);
        }
        
        public WPFShop.ServiceReferenceShop.vwArtist AddArtist(WPFShop.ServiceReferenceShop.vwArtist artist) {
            return base.Channel.AddArtist(artist);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwArtist> AddArtistAsync(WPFShop.ServiceReferenceShop.vwArtist artist) {
            return base.Channel.AddArtistAsync(artist);
        }
        
        public void DeleteArtist(int artistID) {
            base.Channel.DeleteArtist(artistID);
        }
        
        public System.Threading.Tasks.Task DeleteArtistAsync(int artistID) {
            return base.Channel.DeleteArtistAsync(artistID);
        }
        
        public WPFShop.ServiceReferenceShop.vwCustomer AddCustomer(WPFShop.ServiceReferenceShop.vwCustomer customer) {
            return base.Channel.AddCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.vwCustomer> AddCustomerAsync(WPFShop.ServiceReferenceShop.vwCustomer customer) {
            return base.Channel.AddCustomerAsync(customer);
        }
        
        public void DeleteCustomer(int customerID) {
            base.Channel.DeleteCustomer(customerID);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(int customerID) {
            return base.Channel.DeleteCustomerAsync(customerID);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WPFShop.ServiceReferenceShop.CompositeType GetDataUsingDataContract(WPFShop.ServiceReferenceShop.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WPFShop.ServiceReferenceShop.CompositeType> GetDataUsingDataContractAsync(WPFShop.ServiceReferenceShop.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
